name: Code Sign

on:
  push:
    branches:
      - main

jobs:
  sign:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AzureSignTool
      run: |
        dotnet tool install --global AzureSignTool
        dotnet tool restore
      shell: pwsh

    - name: Sign files
      run: |
        $fileFolder = "$env:GITHUB_WORKSPACE\psfiles"
        $files = Get-ChildItem -Path $fileFolder
        foreach ($file in $files) {
            Write-Host $file.FullName
        }
      shell: pwsh
