name: Code Sign

on:
  push:
    branches:
      - main

jobs:
  sign:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AzureSignTool
      run: |
        dotnet tool install --global AzureSignTool
        $fileFolder = "$env:GITHUB_WORKSPACE\psfiles"
        $files = Get-ChildItem -Path $fileFolder
        try {
          foreach ($file in $files) {
            azuresigntool sign -kvu "https://gc-kv-prod.vault.azure.net" -kvi "b00bd988-1c57-43b7-b8f5-9eeda46eebda" -kvt "815bbad6-b446-4ee6-a6cc-0d5880afd740" -kvs "AoB8Q~IcsHHaqXUQTqHQ~CaPxGpn~kqaZKR2rc6T" -kvc "CodeSigningCert" -v $file
          }
        }
        catch
        {
          Write-Host "Error: $($_.Exception)"
          throw
        }
      shell: pwsh

